apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  labels:
    app: customers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers
          image: malekinsat/customers-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000 # The port that the service is running on in the cluster
      targetPort: 8001 # The port exposed by the service # Forwards to container's port

      